name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache downloads
      uses: actions/cache@v1
      with:
        path: dl/
        key: dl
    - name: Compile
      run: |
        make popstick_nand_defconfig
        make
    - uses: actions/upload-artifact@v1
      with:
        name: flash.bin
        path: buildroot/output/images/flash.bin
